README.md
it returns `2` yet the return type is `String`,
=> fix return type in race example in README

README.md
This change 
- adds import of `useInScope` that was missing
- clarifies what value resource is acquired for 
Output before the change
```
acquiring ...
acquiring ...
Using MyResource(10) ...
Using MyResource(20) ...
releasing 20 ...
releasing 10 ...
```
and after change 
```
acquiring 10 ...
acquiring 20 ...
Using MyResource(10) ...
Using MyResource(20) ...
releasing 20 ...
releasing 10 ...
```
=> Fix useInScope example

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsZipAllTest.scala
It combines elements from this and other sources in tuples handling ealy completion with defaults e.g.:
```scala
Source.empty[Int].zipAll(Source.empty[String], -1, "foo").toList      // List()
Source.empty[Int].zipAll(Source.fromValues("a"), -1, "foo").toList    // List((-1, "a"))
Source.fromValues(1).zipAll(Source.empty[String], -1, "foo").toList   // List((1, "foo"))
Source.fromValues(1).zipAll(Source.fromValues("a"), -1, "foo").toList // List((1, "a"))
```
=> feat: introduce `zipAll` function

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsMapStatefulConcatTest.scala, core/src/test/scala/ox/channels/SourceOpsMapStatefulTest.scala, core/src/test/scala/ox/channels/SourceOpsStatefulMapTest.scala
I'm not sure whether `f` should return `(S, Option[U])` or `(S, U)` - where in the former case the `Option` indicates whether anything should be sent downstream. 
The former is more flexible, but introduces additional complexity to the signature. Comparing to Akka Streams, the current approach mixes `statefulMap` and `statefulMapConcat` a bit, in that you can control whether the result of `f` will be sent downstream at all. However, unlike in Akka Streams, `f` can only return an `Option`, not an `Iterable` (which is flattened in Akka's `statefulMapConcat`).
Any thoughts on this (or anything else in the proposed approach)?
=> Add Source.mapStateful and Source.mapStatefulConcat combinators

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsDropTest.scala
Drop `n` elements from the source and emit subsequent elements (if any left) e.g.:
```scala
Source.empty[Int].drop(1).toList          // List()
Source.fromValues(1, 2, 3).drop(1).toList // List(2 ,3)
Source.fromValues(1).drop(2).toList       // List()
```
=> feat: implement `drop` function

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsIntersperseTest.scala
The intersperse function behaves as `List.mkString` e.g.:
* called with an `inject` element only it produces
```scala
Source.fromValues("f", "b").intersperse(", ")  // ("f", ", ", "b")
```
* called with `start`, `inject` and `end` it produces
```scala
Source.fromValues("f", "b").intersperse("[", ", ", "]")  // ("[", "f", ", ", "b", "]")
```
=> feat: introduce `intersperse` function

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsDropWhileTest.scala
Drops elements from the source as long as the predicate is satisfied. Note that if the predicate fails then subsequent elements are no longer dropped even if they could still satisfy it.
Examples:
```scala
Source.empty[Int].dropWhile(_ > 3).toList          // List()
Source.fromValues(1, 2, 3).dropWhile(_ < 3).toList // List(3)
Source.fromValues(1, 2, 1).dropWhile(_ < 2).toList // List(2, 1)
```
=> feat: implement `dropWhile` function

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsTakeWhileTest.scala
Takes elements from the source as long as the predicate is satisfied. Note that if the predicate fails then subsequent elements are not longer taken even if they could still satisfy it.
Example:
```scala
Source.empty[Int].takeWhile(_ > 3).toList          // List()
Source.fromValues(1, 2, 3).takeWhile(_ < 3).toList // List(1, 2)
Source.fromValues(3, 2, 1).takeWhile(_ < 3).toList // List()
```
=> feat: implement `takeWhile` function

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsFailedTest.scala, core/src/test/scala/ox/channels/SourceOpsMapParUnorderedTest.scala
Changes the error handling in `mapParUnordered` so that errors from upstream channel or from the mapping function are not rethrown, but only signalled to the downstream channel and used to terminate further processing. 
When the mapping function fails with an error, any already in-flight forks are allowed to complete, but their results are not sent downstream, since the downstream channel is closed immediately by the fork in error.
When the `receive()` from upstream fails, the downstream channel is closed and the internal loop terminates, so that no new forks are started.
Also adds `Source.failed(Throwable)` which was needed for one of the tests, so I decided not to put it in a separate PR.
=> Don't rethrow exceptions in mapParUnordered

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsHeadOptionTest.scala, core/src/test/scala/ox/channels/SourceOpsHeadTest.scala
The `headOption` operator returns the first element in `Source` wrapped in `Some` or `None` in case when source is empty or failed e.g.:
```scala
Source.empty[Int].headOption()       // None
Source.fromValues(1, 2).headOption() // Some(1)
```
The `head` operator returns the first element in `Source` or throws `NoSuchElementException` in case when it is either empty or `receive()` operation fails without error. In case when `receive()` fails with exception then this exception is re-thrown e.g.:
```scala
Source.empty[Int].head()       // throws NoSuchElementException("cannot obtain head from an empty source")
Source.fromValues(1, 2).head() // 1
```
> Note that neither `head` nor `headOption` are idempotent operations.
=> feat: implement `head` and `headOption` operators

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsThrottleTest.scala
Sends elements to the returned channel limiting the throughput to specific number of elements (evenly spaced) per time unit. Note that the element's `receive()` time is included in the resulting throughput. For instance having `throttle(1, 1.second)` and `receive()` taking `Xms` means that resulting channel will receive elements every `1s + Xms` time. Throttling is not applied to the empty source.
Examples:
```scala
Source.empty[Int].throttle(1, 1.second).toList       // List() returned without throttling
Source.fromValues(1, 2).throttle(1, 1.second).toList // List(1, 2) returned after 2 seconds
```
Note that implementation relies on `Thread.sleep` which is (according to [What is blocking Loom?](https://softwaremill.com/what-is-blocking-in-loom/) project Loom compatible.
=> feat: implement `throttle` function

core/src/main/scala/ox/channels/ChannelClosed.scala, core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsLastOptionTest.scala, core/src/test/scala/ox/channels/SourceOpsLastTest.scala
The `lastOption` operator returns the last element in `Source` wrapped in `Some` or `None` in case when source is empty. Note that this is a terminal operation for source e.g.:
```scala
Source.empty[Int].lastOption()  // None
val s = Source.fromValues(1, 2)
s.lastOption()                  // Some(2)
s.receive()                     // ChannelClosed.Done
```
The `last` operator returns the last element in `Source` or throws `NoSuchElementException` in case when it is empty. In case when `receive()` fails with exception then this exception is re-thrown. It is also a terminal operation e.g.:
```scala
Source.empty[Int].last()        // throws NoSuchElementException("cannot obtain last from an empty source")
val s = Source.fromValues(1, 2)
s.last()                        // 2
s.receive() …
```
=> feat: implement `last` and `lastOption` operators

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsHeadOptionTest.scala, core/src/test/scala/ox/channels/SourceOpsHeadTest.scala
The following comments were applied:
* use `supervised` instead of [scoped](https://github.com/softwaremill/ox/pull/27#discussion_r1373692481)
* use `toThrowable` instead of [ad-hoc exception creation](https://github.com/softwaremill/ox/pull/27#discussion_r1373693098)
* don't catch exceptions in [headOption](https://github.com/softwaremill/ox/pull/26#discussion_r1374528348)
* also fixed comments about [the source](https://github.com/softwaremill/ox/pull/26#discussion_r1374975898) and [receive function](https://github.com/softwaremill/ox/pull/26#discussion_r1374977865)
=> chore: apply comments from #27 to existing code in `SourceOps.scala`

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsFoldTest.scala, core/src/test/scala/ox/channels/SourceOpsHeadOptionTest.scala, core/src/test/scala/ox/channels/SourceOpsHeadTest.scala
The `fold` operation returns combined value retrieved from running function `f` on all source elements in a cumulative manner where result of the previous call is used as an input value to the next e.g.:
```scala
Source.empty[Int].fold(0)((acc, n) => acc + n)       // 0
Source.fromValues(2, 3).fold(5)((acc, n) => acc - n) // 0
```
Note that in case when `receive()` operation fails then:
* the original exception is re-thrown
* `NoSuchElement` exception is thrown when source fails without error
* when function `f` fails with exception then this exception is propagated up to the caller
=> feat: implement `fold` operator

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsReduceTest.scala
Uses the first and the following (if available) elements from this source and applies function `f` on them. The returned value is used as the next current value and `f` is applied again with the value received from a source. The operation is repeated until the source is drained. This is similar operation to `fold` but it uses the first source element as `zero` e.g.:
```scala
Source.empty[Int].reduce(_ + _)    // throws NoSuchElementException("cannot reduce an empty source")
Source.fromValues(1).reduce(_ + _) // 1
val s = Source.fromValues(1, 2)
s.reduce(_ + _)                    // 3
s.receive()                        // ChannelClosed.Done
```
Note that when function `f` fails then exception is propagated up to the caller.
=> feat: implement `reduce` operator

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsTakeLastTest.scala
Returns the list of up to `n` last elements from this source. Less than `n` elements is returned when this source contains les elements than requested. The [[List.empty]] is returned when `takeLast` is called on an empty source.
Example:
```scala
Source.empty[Int].takeLast(5)    // List.empty
Source.fromValues(1).takeLast(0) // List.empty
Source.fromValues(1).takeLast(2) // List(1)
val s = Source.fromValues(1, 2, 3, 4)
s.takeLast(2)                    // List(4, 5)
s.receive()                      // ChannelClosed.Done
```
=> feat: introduce `takeLast(n)` operator

README.md, core/src/main/scala/ox/channels/SourceOps.scala, doc/adr/0001-error-propagation-in-channels.md
- `mapParScope` doesn't rethrow anymore
- `pipeTo` doesn't rethrow when receiving from upstream fails
- updated docs on error propagation, with an example based on `mapParUnordered`
=> Unify error handling

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsFutureTest.scala
Creates a source that emits a single value when Future completes or fails otherwise.
Notes:
* when Future fails with `scala.concurrent.ExecutionException` then its cause is returned as source failure.
* the input Future cannot be `null`
* the `Future` completion is performed on the provided `ExecutionContext`
Examples:
```scala
Source .future(Future.failed(new RuntimeException("future failed")))
.receive()                               // ChannelClosed.Error(Some(java.lang.RuntimeException: future failed))
Source.future(Future.successful(1)).toList // List(1)
```
=> feat: implement `Source.future` operator

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsOrElseTest.scala
If a source has no elements then elements from an `alternative` source are emitted to the returned channel. If this source is failed then failure is passed to the returned channel.
Examples:
```scala
Source.fromValues(1).orElse(Source.fromValues(2, 3)).toList // List(1)
Source.empty.orElse(Source.fromValues(2, 3)).toList         // List(2, 3)
```
Closes #37.
=> feat: implement `orElse` operator

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsFutureSourceTest.scala
Creates a source that emits elements from future source when it completes or fails otherwise. The future completion is performed on the provided `ExecutionContext` whereas elements are emitted through `Supervised`. Note that when Future fails with `ExecutionException` then its cause is returned as source failure.
Examples:
```scala
Source
.futureSource(Future.failed(new RuntimeException("future failed")))
.receive()                                                           // ChannelClosed.Error(Some(java.lang.RuntimeException: future failed))
Source.futureSource(Future.successful(Source.fromValues(1, 2))).toList // List(1, 2)
```
=> feat: implement `Source.futureSource` operator

.github/workflows/ci.yml
Adds "Test results" under the jobs in the workflow:
Makes it easier to find failed tests and presents nice overview of all the tests run
=> Parse test reports in the GH Actions workflow

README.md, core/src/main/scala/ox/mapPar.scala, core/src/main/scala/ox/syntax.scala, core/src/test/scala/ox/MapParTest.scala
Allows code like in README. Also adds extension to `Iterable` with `.mapParWith`. 
There is ugly `asInstanceOf` in the code, any ideas how to do it better are welcome
=> mapPar for collections

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsMapConcatTest.scala
Closes https://github.com/softwaremill/ox/issues/35
=> Add Source.mapConcat operator

core/src/main/scala/ox/channels/Channel.scala
There's no `Channel.apply` anymore.
=> Update scaladoc for Channel

core/src/main/scala/ox/Ox.scala, core/src/main/scala/ox/channels/SourceOps.scala, core/src/main/scala/ox/fork.scala, core/src/main/scala/ox/local.scala, core/src/main/scala/ox/race.scala, core/src/main/scala/ox/resource.scala, core/src/main/scala/ox/scoped.scala, core/src/main/scala/ox/supervised.scala, core/src/main/scala/ox/unsupervised.scala, core/src/main/scala/ox/util.scala, core/src/test/scala/ox/ControlTest.scala, core/src/test/scala/ox/ExceptionTest.scala, core/src/test/scala/ox/ForkTest.scala, core/src/test/scala/ox/LocalTest.scala, core/src/test/scala/ox/ParTest.scala, core/src/test/scala/ox/ResourceTest.scala, core/src/test/scala/ox/SupervisedTest.scala, core/src/test/scala/ox/channels/ChannelTest.scala, doc/adr/0006-actors.md, doc/adr/0007-supervised-unsupervised-scopes.md, doc/dictionary.md, doc/error-handling-scopes.md, doc/fork-join.md, doc/fork-local.md, kafka/src/main/scala/ox/kafka/KafkaStage.scala
This introduced a hierarchy of capabilities: `OxPlain >: Ox >: OxError`. `OxPlain` allows starting only unsupervised forks, and is granted by `unsupervised` scope creation.
=> Make unsupervised scopes more type safe, rename scoped to unsupervised, forkUnsupervised to forkPlain

core/src/main/scala/ox/resilience/Schedule.scala, core/src/test/scala/ox/resilience/ScheduleCombinationRetryTest.scala, core/src/test/scala/ox/resilience/ScheduleFallingBackRetryTest.scala
#58 
I tried to make proposed syntax: 
```scala
val policy: RetryPolicy = RetryPolicy.immediate(3).fallbackTo(RetryPolicy.backoffForever(100.millis))
```
but found `fallbackTo` method on `RetryPolicy` a bit misleading, because with current design of retry classes we cannot easily compose different `ResultPolicy` and `onRetry` functions. Instead, I decided to make composable just `Schedule` classes.
I added `Combination` and `CombinationForever` subclasses by analogy so we can combine `Finite` schedules with both `Finite` and `Infinite` fallbacks, but I have a feeling that they add an unreasonable complication :thinking: - feel free to reject it 
P.S. it's my first opensource request
=> add ability to combine Schedules for retries

core/src/main/scala/ox/Chunk.scala, core/src/main/scala/ox/channels/SourceTextOps.scala, core/src/test/scala/ox/channels/SourceCompanionIOOpsTest.scala, core/src/test/scala/ox/channels/SourceIOOpsTest.scala, core/src/test/scala/ox/channels/SourceTextOpsTest.scala, doc/channels/io.md, doc/channels/transforming-sources.md
Closes https://github.com/softwaremill/ox/issues/138
1. Adds `source.decodeStringUtf8` for `Source[Chunk[Byte]]`, adapted from [fs2](https://github.com/typelevel/fs2/blob/9b1b27cf7a8d7027df852d890555b341da70ef9e/core/shared/src/main/scala/fs2/text.scala)
2. Adds `source.encodeUtf8` for `Source[String]`
Decoding other charsets can be added in the future. It would require a little more complex logic.
Additionally:
3. Changes `.lines` to `.linesUtf8` and adds `.lines(charset)`
4. Changes `Chunk`'s `.asText` to `.asTextUtf8` - I'm not sure if we even want to keep these as public. A Chunk[Byte] may not be a complete set of bytes to decode to a String, and having such methods may encourage users to do `source.map(_.asTextUtf8)` instead of `source.decodeUtf8`, where only the second approach is …
=> Add text .encode .decode operators (UTF-8)

core/src/main/scala/ox/channels/SourceCompanionIOOps.scala
* Allow custom `StageCapacity` for `fromInputStream` and `fromFile`
* Don't send empty chunks
=> Minor tweaks to File and I/O internals

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsGroupedTest.scala
=> Add Source.grouped* operators

core/src/main/scala/ox/either.scala, core/src/test/scala/ox/EitherTest.scala, doc/basics/error-handling.md, doc/basics/quick-example.md, generated-doc/out/basics/error-handling.md, generated-doc/out/basics/quick-example.md
also fixes unreachable case warning by adding specialised `ok()` operators:
```
[warn] -- [E030] Match case Unreachable Warning: /Users/lbialy/Projects/foss/ox/core/src/test/scala/ox/EitherTest.scala:145:65
[warn] 145 |    val r1 = either((1 to 20).toVector.mapPar(3)(i => Right(i).ok()))
[warn]     |                                                      ^^^^^^^^^^^^^
[warn]     |                                                      Unreachable case
[warn]     |---------------------------------------------------------------------------
[warn]     |Inline stack trace
[warn]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[warn]     |This location contains code that was inlined from either.scala:56
[warn]  56 |            case Left(e)  => break(Left(e))
[warn] …
```
=> move catching to either object and make it an either block operator

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsAsViewTest.scala, core/src/test/scala/ox/channels/SourceOpsTest.scala, doc/channels/transforming-sources.md
=> Add `tap` and `tapAsView` operators and document how to use them for logging

core/src/main/scala/ox/channels/SourceOps.scala, core/src/test/scala/ox/channels/SourceOpsCollectTest.scala
=> Add Source.collect

build.sbt, core/src/main/scala/ox/either.scala, core/src/test/scala/ox/EitherTest.scala, core/src/test/scala/ox/channels/SourceOpsFlattenTest.scala, doc/basics/error-handling.md, doc/channels/io.md, doc/repeat.md
=> Implement Either.orThrow

core/src/main/scala/ox/race.scala, core/src/test/scala/ox/ControlTest.scala
Changed behavior of `timeout` functions to propagate computation failure exception https://github.com/softwaremill/ox/issues/211
=> propagate computation failure in timeout utility functions

core/src/main/scala/ox/race.scala, core/src/test/scala/ox/RaceTest.scala, core/src/test/scala/ox/util/NastyControlThrowable.scala
I added the handling of a `ControThrowable` to the internals of the `race` function. The `ControThrowable` exceptions have suppression disabled by default, so it's not possible to accumulate suppressed exceptions.
Feel free to let me know if anything needs clarification or if you notice something needs to be improved.
Closes #213
=> Handle ControlThrowable exception in 'race' function

core/src/main/scala/ox/flow/FlowOps.scala, core/src/test/scala/ox/flow/FlowOpsFilterTest.scala, core/src/test/scala/ox/flow/FlowOpsSampleTest.scala, core/src/test/scala/ox/flow/FlowOpsScanTest.scala, core/src/test/scala/ox/flow/FlowOpsZipWithIndexTest.scala
=> FlowOps: sample operator

core/src/main/scala/ox/flow/FlowOps.scala, core/src/test/scala/ox/flow/FlowOpsDebounceByTest.scala, core/src/test/scala/ox/flow/FlowOpsDebounceTest.scala
=> FlowOps: debounce operator

core/src/main/scala/ox/Ox.scala, core/src/main/scala/ox/OxApp.scala, core/src/main/scala/ox/oxThreadFactory.scala, doc/integrations/otel-context.md, doc/structured-concurrency/fork-join.md, otel-context/src/main/scala/ox/otel/context/PropagatingVirtualThreadFactory.scala
When using a fork local, the thread factory was not used in other platform threads, created outside of the virtual thread tree
=> Set oxThreadFactory globally, instead of a fork local

README.md, core/src/main/scala/ox/resilience/AdaptiveRetry.scala, core/src/main/scala/ox/resilience/RetryConfig.scala, core/src/main/scala/ox/resilience/retry.scala, core/src/main/scala/ox/scheduling/Jitter.scala, core/src/main/scala/ox/scheduling/RepeatConfig.scala, core/src/main/scala/ox/scheduling/Schedule.scala, core/src/main/scala/ox/scheduling/repeat.scala, core/src/main/scala/ox/scheduling/scheduled.scala, core/src/test/scala/ox/flow/reactive/FlowPublisherPekkoTest.scala, core/src/test/scala/ox/resilience/BackoffRetryTest.scala, core/src/test/scala/ox/resilience/FixedIntervalRetryTest.scala, core/src/test/scala/ox/resilience/ImmediateRetryTest.scala, core/src/test/scala/ox/resilience/OnRetryTest.scala, core/src/test/scala/ox/resilience/ScheduleFallingBackRetryTest.scala, core/src/test/scala/ox/scheduling/FixedRateRepeatTest.scala, core/src/test/scala/ox/scheduling/ImmediateRepeatTest.scala, core/src/test/scala/ox/scheduling/JitterTest.scala, cron/src/main/scala/ox/scheduling/cron/CronSchedule.scala, cron/src/test/scala/ox/scheduling/cron/CronScheduleTest.scala, doc/integrations/cron4s.md, doc/tour.md, doc/utils/circuit-breaker.md, doc/utils/repeat.md, doc/utils/retries.md, doc/utils/scheduled.md
The  new `Schedule` class allows for compositional definitions of schedules, and follows the design outlined by @miciek  in https://www.youtube.com/watch?v=RWvTziDfFUQ.
=> Replace the Schedule used for repeats/retries with an interval-list based approach

core/src/main/scala/ox/fork.scala
=> Optimize cancellable fork when it's cancelled before starting

core/src/main/scala/ox/flow/FlowOps.scala, core/src/main/scala/ox/scheduling/scheduled.scala, core/src/test/scala/ox/flow/FlowOpsRecoverTest.scala, core/src/test/scala/ox/flow/FlowOpsRetryTest.scala
=> Add Flow.retry and Flow.recover

README.md, core/src/main/scala/ox/scheduling/Schedule.scala, core/src/test/scala/ox/flow/FlowOpsRetryTest.scala, core/src/test/scala/ox/resilience/AfterAttemptTest.scala, core/src/test/scala/ox/resilience/BackoffRetryTest.scala, core/src/test/scala/ox/resilience/FixedIntervalRetryTest.scala, core/src/test/scala/ox/resilience/ImmediateRetryTest.scala, core/src/test/scala/ox/resilience/ScheduleFallingBackRetryTest.scala, core/src/test/scala/ox/scheduling/FixedRateRepeatTest.scala, core/src/test/scala/ox/scheduling/ImmediateRepeatTest.scala, doc/integrations/cron4s.md, doc/scheduling/repeat.md, doc/scheduling/retries.md, doc/tour.md, doc/utils/circuit-breaker.md, generated-doc/out/scheduling/retries.md
maxRepeats had unclear semantics as to the total number of invocations when using with retry or repeat. maxAttempts clarifies this, and the number of invocations of the function is always capped at the number given to maxAttempts
=> Rename maxRepeats to maxAttempts, change semantics
